package com.norbitltd.spoiwo.model

object TableStyleName {

  lazy val TableStyleLight1 = TableStyleName("TableStyleLight1")
  lazy val TableStyleLight2 = TableStyleName("TableStyleLight2")
  lazy val TableStyleLight3 = TableStyleName("TableStyleLight3")
  lazy val TableStyleLight4 = TableStyleName("TableStyleLight4")
  lazy val TableStyleLight5 = TableStyleName("TableStyleLight5")
  lazy val TableStyleLight6 = TableStyleName("TableStyleLight6")
  lazy val TableStyleLight7 = TableStyleName("TableStyleLight7")
  lazy val TableStyleLight8 = TableStyleName("TableStyleLight8")
  lazy val TableStyleLight9 = TableStyleName("TableStyleLight9")
  lazy val TableStyleLight10 = TableStyleName("TableStyleLight10")
  lazy val TableStyleLight11 = TableStyleName("TableStyleLight11")
  lazy val TableStyleLight12 = TableStyleName("TableStyleLight12")
  lazy val TableStyleLight13 = TableStyleName("TableStyleLight13")
  lazy val TableStyleLight14 = TableStyleName("TableStyleLight14")
  lazy val TableStyleLight15 = TableStyleName("TableStyleLight15")
  lazy val TableStyleLight16 = TableStyleName("TableStyleLight16")
  lazy val TableStyleLight17 = TableStyleName("TableStyleLight17")
  lazy val TableStyleLight18 = TableStyleName("TableStyleLight18")
  lazy val TableStyleLight19 = TableStyleName("TableStyleLight19")
  lazy val TableStyleLight20 = TableStyleName("TableStyleLight20")
  lazy val TableStyleLight21 = TableStyleName("TableStyleLight21")

  lazy val TableStyleMedium1 = TableStyleName("TableStyleMedium1")
  lazy val TableStyleMedium2 = TableStyleName("TableStyleMedium2")
  lazy val TableStyleMedium3 = TableStyleName("TableStyleMedium3")
  lazy val TableStyleMedium4 = TableStyleName("TableStyleMedium4")
  lazy val TableStyleMedium5 = TableStyleName("TableStyleMedium5")
  lazy val TableStyleMedium6 = TableStyleName("TableStyleMedium6")
  lazy val TableStyleMedium7 = TableStyleName("TableStyleMedium7")
  lazy val TableStyleMedium8 = TableStyleName("TableStyleMedium8")
  lazy val TableStyleMedium9 = TableStyleName("TableStyleMedium9")
  lazy val TableStyleMedium10 = TableStyleName("TableStyleMedium10")
  lazy val TableStyleMedium11 = TableStyleName("TableStyleMedium11")
  lazy val TableStyleMedium12 = TableStyleName("TableStyleMedium12")
  lazy val TableStyleMedium13 = TableStyleName("TableStyleMedium13")
  lazy val TableStyleMedium14 = TableStyleName("TableStyleMedium14")
  lazy val TableStyleMedium15 = TableStyleName("TableStyleMedium15")
  lazy val TableStyleMedium16 = TableStyleName("TableStyleMedium16")
  lazy val TableStyleMedium17 = TableStyleName("TableStyleMedium17")
  lazy val TableStyleMedium18 = TableStyleName("TableStyleMedium18")
  lazy val TableStyleMedium19 = TableStyleName("TableStyleMedium19")
  lazy val TableStyleMedium20 = TableStyleName("TableStyleMedium20")
  lazy val TableStyleMedium21 = TableStyleName("TableStyleMedium21")
  lazy val TableStyleMedium22 = TableStyleName("TableStyleMedium22")
  lazy val TableStyleMedium23 = TableStyleName("TableStyleMedium23")
  lazy val TableStyleMedium24 = TableStyleName("TableStyleMedium24")
  lazy val TableStyleMedium25 = TableStyleName("TableStyleMedium25")
  lazy val TableStyleMedium26 = TableStyleName("TableStyleMedium26")
  lazy val TableStyleMedium27 = TableStyleName("TableStyleMedium27")
  lazy val TableStyleMedium28 = TableStyleName("TableStyleMedium28")

  lazy val TableStyleDark1 = TableStyleName("TableStyleDark1")
  lazy val TableStyleDark2 = TableStyleName("TableStyleDark2")
  lazy val TableStyleDark3 = TableStyleName("TableStyleDark3")
  lazy val TableStyleDark4 = TableStyleName("TableStyleDark4")
  lazy val TableStyleDark5 = TableStyleName("TableStyleDark5")
  lazy val TableStyleDark6 = TableStyleName("TableStyleDark6")
  lazy val TableStyleDark7 = TableStyleName("TableStyleDark7")
  lazy val TableStyleDark8 = TableStyleName("TableStyleDark8")
  lazy val TableStyleDark9 = TableStyleName("TableStyleDark9")
  lazy val TableStyleDark10 = TableStyleName("TableStyleDark10")
  lazy val TableStyleDark11 = TableStyleName("TableStyleDark11")
}

case class TableStyleName private (value: String) {
  override def toString: String = value
}
