package spoiwo.model

object TableStyleName {

  lazy val TableStyleLight1: TableStyleName = TableStyleName("TableStyleLight1")
  lazy val TableStyleLight2: TableStyleName = TableStyleName("TableStyleLight2")
  lazy val TableStyleLight3: TableStyleName = TableStyleName("TableStyleLight3")
  lazy val TableStyleLight4: TableStyleName = TableStyleName("TableStyleLight4")
  lazy val TableStyleLight5: TableStyleName = TableStyleName("TableStyleLight5")
  lazy val TableStyleLight6: TableStyleName = TableStyleName("TableStyleLight6")
  lazy val TableStyleLight7: TableStyleName = TableStyleName("TableStyleLight7")
  lazy val TableStyleLight8: TableStyleName = TableStyleName("TableStyleLight8")
  lazy val TableStyleLight9: TableStyleName = TableStyleName("TableStyleLight9")
  lazy val TableStyleLight10: TableStyleName = TableStyleName("TableStyleLight10")
  lazy val TableStyleLight11: TableStyleName = TableStyleName("TableStyleLight11")
  lazy val TableStyleLight12: TableStyleName = TableStyleName("TableStyleLight12")
  lazy val TableStyleLight13: TableStyleName = TableStyleName("TableStyleLight13")
  lazy val TableStyleLight14: TableStyleName = TableStyleName("TableStyleLight14")
  lazy val TableStyleLight15: TableStyleName = TableStyleName("TableStyleLight15")
  lazy val TableStyleLight16: TableStyleName = TableStyleName("TableStyleLight16")
  lazy val TableStyleLight17: TableStyleName = TableStyleName("TableStyleLight17")
  lazy val TableStyleLight18: TableStyleName = TableStyleName("TableStyleLight18")
  lazy val TableStyleLight19: TableStyleName = TableStyleName("TableStyleLight19")
  lazy val TableStyleLight20: TableStyleName = TableStyleName("TableStyleLight20")
  lazy val TableStyleLight21: TableStyleName = TableStyleName("TableStyleLight21")

  lazy val TableStyleMedium1: TableStyleName = TableStyleName("TableStyleMedium1")
  lazy val TableStyleMedium2: TableStyleName = TableStyleName("TableStyleMedium2")
  lazy val TableStyleMedium3: TableStyleName = TableStyleName("TableStyleMedium3")
  lazy val TableStyleMedium4: TableStyleName = TableStyleName("TableStyleMedium4")
  lazy val TableStyleMedium5: TableStyleName = TableStyleName("TableStyleMedium5")
  lazy val TableStyleMedium6: TableStyleName = TableStyleName("TableStyleMedium6")
  lazy val TableStyleMedium7: TableStyleName = TableStyleName("TableStyleMedium7")
  lazy val TableStyleMedium8: TableStyleName = TableStyleName("TableStyleMedium8")
  lazy val TableStyleMedium9: TableStyleName = TableStyleName("TableStyleMedium9")
  lazy val TableStyleMedium10: TableStyleName = TableStyleName("TableStyleMedium10")
  lazy val TableStyleMedium11: TableStyleName = TableStyleName("TableStyleMedium11")
  lazy val TableStyleMedium12: TableStyleName = TableStyleName("TableStyleMedium12")
  lazy val TableStyleMedium13: TableStyleName = TableStyleName("TableStyleMedium13")
  lazy val TableStyleMedium14: TableStyleName = TableStyleName("TableStyleMedium14")
  lazy val TableStyleMedium15: TableStyleName = TableStyleName("TableStyleMedium15")
  lazy val TableStyleMedium16: TableStyleName = TableStyleName("TableStyleMedium16")
  lazy val TableStyleMedium17: TableStyleName = TableStyleName("TableStyleMedium17")
  lazy val TableStyleMedium18: TableStyleName = TableStyleName("TableStyleMedium18")
  lazy val TableStyleMedium19: TableStyleName = TableStyleName("TableStyleMedium19")
  lazy val TableStyleMedium20: TableStyleName = TableStyleName("TableStyleMedium20")
  lazy val TableStyleMedium21: TableStyleName = TableStyleName("TableStyleMedium21")
  lazy val TableStyleMedium22: TableStyleName = TableStyleName("TableStyleMedium22")
  lazy val TableStyleMedium23: TableStyleName = TableStyleName("TableStyleMedium23")
  lazy val TableStyleMedium24: TableStyleName = TableStyleName("TableStyleMedium24")
  lazy val TableStyleMedium25: TableStyleName = TableStyleName("TableStyleMedium25")
  lazy val TableStyleMedium26: TableStyleName = TableStyleName("TableStyleMedium26")
  lazy val TableStyleMedium27: TableStyleName = TableStyleName("TableStyleMedium27")
  lazy val TableStyleMedium28: TableStyleName = TableStyleName("TableStyleMedium28")

  lazy val TableStyleDark1: TableStyleName = TableStyleName("TableStyleDark1")
  lazy val TableStyleDark2: TableStyleName = TableStyleName("TableStyleDark2")
  lazy val TableStyleDark3: TableStyleName = TableStyleName("TableStyleDark3")
  lazy val TableStyleDark4: TableStyleName = TableStyleName("TableStyleDark4")
  lazy val TableStyleDark5: TableStyleName = TableStyleName("TableStyleDark5")
  lazy val TableStyleDark6: TableStyleName = TableStyleName("TableStyleDark6")
  lazy val TableStyleDark7: TableStyleName = TableStyleName("TableStyleDark7")
  lazy val TableStyleDark8: TableStyleName = TableStyleName("TableStyleDark8")
  lazy val TableStyleDark9: TableStyleName = TableStyleName("TableStyleDark9")
  lazy val TableStyleDark10: TableStyleName = TableStyleName("TableStyleDark10")
  lazy val TableStyleDark11: TableStyleName = TableStyleName("TableStyleDark11")
}

case class TableStyleName private (value: String) {
  override def toString: String = value
}
